##
# Config for RTD 1.0.1 (http://dev.bukkit.org/server-mods/rtd/)
# Config suggestions from Zachary DuBois (https://accountproductions.com/)
#
# Problem? Suggestion? File an issue!
# http://github.com/x3chaos/RTD/issues
#
#   Default config created specifically for Bukkit without plugins.
#   To avoid command conflicts, make sure that the command is
#   exactly as it would be entered into the console or chat.
#
#      => You can make this plugin compatible with any other plugin's
#         commands! Just edit this file to accommodate the command(s)
#         that you want.
##
#   Available variables:
#   - {player}
#     Replaced with the player's display name
#		- {rplayer}
#			Replaced with a random player's name
#		- {world}
#			Replaced with the name of the player's world
#		- {rtime:xx-xx}
#			Replaced with a random number (time) within the given range, inclusively.
#     NOTE: Maxes at 24000 (same as Minecraft time) 
##
#   Important notes:
#   => Variables must be inside {curly braces}!
#   => Only the variables listed above are valid.
#   => The leading slash (e.g. "/" in "/say") is optional.
#       => It is, however, recommended.
##

options:
    cooldown: 30

outcomes:
    diamond:
        - console=/say {player} rolled diamond!
        - console=/give {player} 264
    death:
        - console=/say {player} rolled DEATH!
        - player=/kill
    light:
        - console=/say {player} rolled light!
        - console=/give {player} 50 64
        - console=/give {player} 89 64
    daytime:
        - console=/say {player} rolled daytime!
        - console=/time set {rtime:0-12000}
    night:
        - console=/say {player} rolled night!
        - console=/time set {rtime:12000-24000}