##
#   RTD config.yml
#   BukkitDev: http://dev.bukkit.org/server-mods/rtd/
##
#	Options:
#		- preferred-channel
#			"stable" or "beta", WITHOUT quotes.
#			Will warn the owner/admin when an update
#			is available for the given channel.
##
#   Available variables:
#       - {player}
#           Replaced with the player's display name
#		- {rplayer}
#			Replaced with a random player's name
#		- {world}
#			Replaced with the name of the player's world
#		- {rtime:xx-xx}
#			Replaced with a random number (time) within
#			the given range (e.g. 0-1000), inclusively
##
#   EXAMPLES:
# outcomes:
#     diamond:
#     - console=/give {player} diamond
#     - console=/say {player} rolled for a diamond!
#     death:
#     - player=/kill
#     - console=/say {player} rolled for DEATH
##
#   Important notes:
#   - Variables must be inside {curly braces}!
#   - Only the variables listed above are valid.
#   - The leading slash (e.g. "/" in "/say") is optional.
#       => It is, however, recommended.
##

options:
	preferred-channel: stable
    cooldown: 30

outcomes:
    diamond:
        - console=/give {player} 264
        - console=/say {player} rolled for a diamond!
    death:
        - player=/kill
        - console=/say {player} rolled for DEATH!